services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: covid-cases
    restart: always
    command: npm start
    environment:
      - PROD_MONGO_URL=mongodb+srv://<user>:<password>@<cluster>.hp8av.mongodb.net/<database>?retryWrites=true&w=majority
    volumes:
      - ./dist:/usr/src/covid-daily-cases/dist
    ports:
      - "3333:3333"
    links:
      - mongo